---
title: Looset
author: João Paulo
email: JpSoares106@gmail.com
description: Source code visualization - An explorer for big or unknown projects
baseurl: "/looset-landing"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
