---
title: Looset - A source code explorer for big or unknown projects
author: João Paulo
email: JpSoares106@gmail.com
description: ''
baseurl: "/looset-landing"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
